sudo: false
language: java
jdk:
- oraclejdk7
after_success:
- "./gradlew coveralls"
- "./gradlew bintrayUpload"
cache:
  directories:
  - "$HOME/.gradle/wrapper"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/caches/2.6"
  - "$HOME/.gradle/caches/modules-2/files-2.1"
  - "$HOME/.gradle/caches/modules-2/metadata-2.15"
env:
  global:
  - secure: mr53MEVJbgt9kdVTdnfYDz46pqWzTPeLSdajyMiCMED5FVebJ6bISHE/R/NQqmLT1dIk5Y3FqRXZmeJpc9OCVf16s198X9/zFJtbgn8werIk9JAbB+6imR0wDDAxQ3Ce155BFvjNT9f4lmdKiGPmAIrKOxp6J/0ONr2d0/Bn7kQ6LOquviZrHXE5N/z1MSR2OTQsVe7PM9pyMJPhKeYEGaHv5fIzTNfra0oA9WxFRw6XiXQUNxT0u9q0reZ43n3sOfQ0tGuvv17QSvgiIBnFnHZAb0e9+Pq99LD/q1w3+CVT3K7hCmMg0HWgzEDfCVE34tiWEPUmv5DX5F7SxK7MHIvFfyy0R9hs41l5B1Vp77zujJN8DZna4dOCtg26m5UF53Fx/jTgIj1wpvzToeijwYsK86g5wDDnqJFoxUV5u7Tcai1dwShpT818AhqlWnz3svhQNLv0l3bQINl6b08Xec1kaGz7Euyu9yoV+jOxcumgiZbj04lszamDrJ4t4Sp+YuQCgdPXi5UkOzibUp08AhITfKtNIkI6nRHxuGsiJ5yq1TTVL+xuzoi9iV9sOToU7G51WvLW4Pa4hAI1/q4FteXChn/aP8OYFYCHeZoTpWWEunXBZFa3RKPtZb0p5Mh+f8Dx0Aa7YvEoMWKuYcwM073vRi1NtLPPcCXolPSdis8=
  - secure: aeu79W9QbQQzeuQ9K1oFR5iIogsdzGlZhitgNDAy2JXOpFsPvK4cxnR/faGO8m0YTHPEnQsY01THu6J5P73iaCJ+CZQh64QYO4w2sgfEDKlyKqZ8fPDdVGJay3Nbfmf0aex815r7R75777/+OmBYpnU1Ll89vMaO4Z8c6nnMBtPiXGrRtz/WTfc4TmF0vMxr1V34hjb3JTPG/sWGH3YjopDjEhyp3a5rv9e6K+0wBFCKZaWpQRJGkcxra7FGM1N4ZXYTuJrqFyA92Qx5LnCH8CrAXGIgtJJTRiiMD9Wtb/HPoDCZKmSrsV+G6rKfLfohjuq58KTLXOOmsPTUZ+8uNU2yiPOHzklQ9AGJHZpHs35PgwgDmt/F/cciozMrK95DnDn2XbT9UVehuXt5fnppYAkFLYYysvuKeHxhg9Ltfkwm4cZReImBDCscp9H6aUCkfqSPCh6nKTaKoDhATk1B2a20KhDY0nM6Z+Va/MTllTn44Tjtc1EvJ0oQTxOJKb2k+myhw8mOB2/TS1mierDUq+YfZ53d5/UImMeltp0b7FCIde6yY6lRFr6ad9P9+O5H0lXj8YBeuomLoyiY0aDAI0WDDW3h1AWftedVELKkYQesOvwstqUylPq3nymKJGjtIWd1cVHtAFNoiSQkOWnZzc/PCmO9DrmPUl1JTvcTYEo=
